[package]
name = "butterpollo-truehdr"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
rust-version = "1.88"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common"] }

[profile.release]
panic = "abort"
lto = "thin"
strip = "debuginfo"
